#include <iostream>
#include <cmath>
using namespace std;

int main()
{
    int x1, y1, x2, y2;

    cout << "Enter starting point (x1, y1): ";
    cin >> x1 >> y1;

    cout << "Enter ending point (x2, y2): ";
    cin >> x2 >> y2;

    int dx = abs(x2 - x1);
    int dy = abs(y2 - y1);

    int sx = (x1 < x2) ? 1 : -1;
    int sy = (y1 < y2) ? 1 : -1;

    int error = dx - dy;

    cout << "\nPoints generated by Bresenham:\n";

    while (true)
    {
        cout << "(" << x1 << ", " << y1 << ")" << endl;

        if (x1 == x2 && y1 == y2)
            break;

        int e2 = 2 * error;

        if (e2 > -dy)
        {
            error = error - dy;
            x1 = x1 + sx;
        }

        if (e2 < dx)
        {
            error = error + dx;
            y1 = y1 + sy;
        }
    }

    return 0;
}
