#include <iostream>
#include <cmath>
#include <algorithm>

using namespace std;

int main()
{
    int x1, y1, x2, y2;

    cout << "Enter starting point (x1, y1): ";
    cin >> x1 >> y1;

    cout << "Enter ending point (x2, y2): ";
    cin >> x2 >> y2;

    int dx = x2 - x1;
    int dy = y2 - y1;

    int steps = max(abs(dx), abs(dy));

    cout << "\nPoints generated by DDA:\n";

    // If both points are the same
    if (steps == 0)
    {
        cout << "(" << x1 << ", " << y1 << ")" << endl;
        return 0;
    }

    float xIncrement = static_cast<float>(dx) / steps;
    float yIncrement = static_cast<float>(dy) / steps;

    float x = x1;
    float y = y1;

    for (int i = 0; i <= steps; i++)
    {
        cout << "(" << round(x) << ", " << round(y) << ")" << endl;

        x += xIncrement;
        y += yIncrement;
    }

    return 0;
}